# Generated by Django 4.1 on 2022-08-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
    ]
