# Generated by Django 4.1 on 2022-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220817_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='test',
            field=models.CharField(default='', max_length=2),
        ),
    ]
